### ISSUE TITLE
Dependencies fail to load in PlatformIO

### ISSUE THREAD

**Issue by MrHyrex** [khoih-prog/AsyncMQTT_Generic#5]
### Describe the bug

When building a project for Portenta in PlatformIO depending on AsyncMQTT_Generic, multiple errors are thrown, all seems to be related to missing stm32_def.h file. Possibly because the khoih-prog/Portenta_H7_AsyncTCP dependency fails to install.

### Steps to Reproduce

- Create new project fro Portenta H7 in platform IO
- Add AsynqMQTT_Generic to the project using project manager.
- Build.

### Expected behavior

The blank program should build without issues

### Actual behavior

Fails to build.
Dependcy khoih-prog/Portenta_H7_AsyncTCP fails to install
Multiple errors related to missing stm32_def.h file

When using the included [platformio.ini](https://github.com/khoih-prog/AsyncMQTT_Generic/blob/main/platformio/platformio.ini) file, the build crashes with the following info/error:
`Library Manager: Installing stm32duino/STM32duino STM32Ethernet @ >=1.2.0
Error: Could not find the package with 'stm32duino/STM32duino STM32Ethernet @ >=1.2.0' requirements for your system 'windows_amd64'`

Also, possibly unrelated, Vscode displays the following error during installation of the libraray:
`Error: Multiple requests to rebuild the project "<name>" index have been received! Automatic index rebuilding process has been terminated for 10 minutes.`

### Information

- Platform IO version: Core 6.0.1·Home 3.4.1
- Vscode version: 1.67.2
- Windows 10 Business

### Additional context

It looks like the repository path for the Portenta_H7_AsyncTCP libraray is messed up on the platform.io site: (https://registry.platformio.org/libraries/khoih-prog/Portenta_H7_AsyncTCP)

![image](https://user-images.githubusercontent.com/97226308/169816025-89451fc1-9e34-45d7-8e7c-228e7bc37566.png)

**Comment by khoih-prog** [comment]
Hi,

Thanks for your interest in the library.

The issue is similar to [**Compile error with ESP8266 and Platformio** #25](https://github.com/khoih-prog/AsyncHTTPRequest_Generic/issues/25) and many more issues. The general answer is as follows : 

As you know, using PIO requires a little more experiences and knowledge than Arduino IDE to understand and manually modify the settings. Moreover, the current PIO version is **not smart enough to select the correct library, according the board,** necessary to use with this library, which is written mainly for **multi-platforms** and Arduino IDE.

**Just try using Arduino IDE and understand why it can selects correctly the libraries to use, no matter boards / platforms you're using.**

This library's `platformio.ini` is also written to **include all possible dependent libraries for all the boards with the expectation that PIO users will know and modify to ignore the incorrect ones**. It's better than include nothing and users has to do research to know which libraries are needed and include them.

Just understand which libraries to be used for your board, you'll know that you can **ignore some unused libraries**, such as adding to your `platformio.ini`

```
lib_ignore = 
   STM32AsyncTCP
   STM32duino LwIP
   STM32Ethernet
   WebServer_WT32_ETH01
```

Good Luck,

---

> 
> ### Additional context
> 
> It looks like the repository path for the Portenta_H7_AsyncTCP libraray is messed up on the platform.io site: (https://registry.platformio.org/libraries/khoih-prog/Portenta_H7_AsyncTCP)
> 
> ![image](https://user-images.githubusercontent.com/97226308/169816025-89451fc1-9e34-45d7-8e7c-228e7bc37566.png)


Thanks, will fix.

**Comment by MrHyrex** [comment]
Ok, thanks will check out that forum.

Tried the install again with same result. Maybe I'm misunderstaning something, but the latest version of AsyncMqtt_Generic library available in the Platform IO library manager is still v1.5.0 which tries (and fails) to install v1.3.0 of the Portenta_H7_AsyncTCP libraray.

**Comment by khoih-prog** [comment]
It there is something wrong with the installation, you can install any library manually, by using command, such as

```
$ pio pkg install --global -l "khoih-prog/Portenta_H7_AsyncTCP"
```
